### ISSUE TITLE
Create static website with pre-run notebooks

### ISSUE THREAD

**Issue by apuignav** [scikit-hep/scikit-hep-tutorials#1]
I think that would be a very useful addition to this repo, probably using https://nbsphinx.readthedocs.io/en/0.4.2/pre-executed.html.

**Comment by eduardo-rodrigues** [comment]
This is not forgotten. @henryiii recently mentioned [jupyter-book](https://jupyterbook.org/intro) to me and that could be a neat way to do what this "issue" suggests.

**Comment by henryiii** [comment]
I'm going to be looking into setting this up via CI in the near future. So far it's looking promising; the Jupyter notebooks can easily be run in Binder and even single cells can be run, but you also get a nice gitbook-like static interface. JupyterLab 2.0 has better built-in support for producing good Jupyterbooks.

The Sphinx extension is great, but really best at extending docs. I'm using it in [boost-histogram's docs for examples](https://boost-histogram.readthedocs.io/en/latest/notebooks/xarray.html). Jupyterbook is slightly more powerful and nicer, without having to set up the rest of Sphinx.

**Comment by eduardo-rodrigues** [comment]
Hi @henryiii, should we not close this task at this point now that we have the tutorials served at https://scikit-hep.org/scikit-hep-tutorials in a Jupyter book? Unless I am missing something else you may have in mind? Thanks.

**Comment by henryiii** [comment]
Yes, this was setup some time ago, so this is closable.  :)
