### ISSUE TITLE
environment.yaml for tutorials

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/scikit-hep-tutorials#6]
As @henryiii said:

> There is a scikit-hep meta package for PyPI (not available on conda-forge yet). Also, if you use the same version of the same package in multiple conda environments, conda shares the packages for you - you only have one copy and then have links. But I do think we could have a recommended “environment.yml” that we could provide in the tutorial repo.

I think we could make an `environment.yaml` for the tutorials to build up the test environment.

Possible Reference:
- @eduardo-rodrigues's https://github.com/eduardo-rodrigues/2020-03-04_DESY_Scikit-HEP_HandsOn
- @LovelyBuggies's https://nino-hist.site/en/latest/user-guide/integration.html

**Comment by henryiii** [comment]
There should be one in my PR, since the CI needs it to run Jupyter book (needs to be expanded further, probably, and if users are supposed to use it as a template, it probably shouldn't have jupyter-book and maybe ROOT).

**Comment by LovelyBuggies** [comment]
Ok, I will expand some dependencies once it's merged.

**Comment by eduardo-rodrigues** [comment]
It's a shame that I still have not managed to give the `scikit-hep`metapackage the little push it needs now to be released. Indeed that would be an easy way to provide an environment consistent among "all" packages in the org, plus a bunch of other ones that are needed.

My link you refer to above is for a tutorial I gave at DESY. There I created an environment file by hand. It's a consistent set, so a good example. You may have noticed that I started adapting bits of that to this package, see PR https://github.com/scikit-hep/scikit-hep-tutorials/pull/4.

Great to see activity here :-)!

**Comment by LovelyBuggies** [comment]
> My link you refer to above is for a tutorial I gave at DESY. There I created an environment file by hand. It's a consistent set, so a good example. You may have noticed that I started adapting bits of that to this package, see PR 4.

1. **Env:** I was happy to see that your environment.yml is pretty complete. *Though we need to fine-tune and support the latest version, e.g. `boost-histogram>=0.6.2, <0.7`.* And I suggest adding the dependencies one by one, i.e., modifying the corresponding dependencies when adding new notebooks, rather than moving them all at one time.
2. **Contents:** Yes, I saw your PR of unit.ipynb. Still much work to be done here, which should include but not be limited to the DESY tutorials. And we are not supposed to forget the changes caused by the env version issue mentioned above either :)

**Comment by eduardo-rodrigues** [comment]
Yep. At least we have now some activity going on, and that's nice. Thanks.

**Comment by eduardo-rodrigues** [comment]
@LovelyBuggies, still interested in finalising this? As you can see from https://github.com/scikit-hep/scikit-hep/releases I finally pushed that extra work through and we now have `scikit-hep` metapackage releases :-).

**Comment by eduardo-rodrigues** [comment]
Getting back to this - I've now made several releases of the metapackage so time to adapt the environment.yaml file to use those releases, I reckon. I will try and push a PR soon and we see, @henryiii and @LovelyBuggies.
